### ISSUE TITLE
RestSharp AddFile method not found

### ISSUE THREAD

**Issue by damonjanis** [mxenabled/atrium-csharp#13]
Using the latest version of RestSharp (106.11.4) produces this runtime error in atrium-csharp: "Method not found: 'RestSharp.IRestRequest RestSharp.RestRequest.AddFile(System.String, System.Action`1<System.IO.Stream>, System.String, System.String)'."

The docs say atrium-csharp is dependent on RestSharp 105.1.0. Is it incompatible with more recent versions?

**Comment by brettmortensen** [comment]
@damonjanis Thanks for reaching out and bringing attention to this issue 👍 

I can confirm that our library is currently not compatible with recent versions of RestSharp. RestSharp added an additional parameter to the method shown in your error above, making the method we are using "not found" when attempting to use version 106.11.4 

I'll be updating the README to reflect the current state.

**Comment by brettmortensen** [comment]
README updated here: https://github.com/mxenabled/atrium-csharp/pull/15

Thanks again for reaching out.
