### ISSUE TITLE
Enhancement:  BaseUrl

### ISSUE THREAD

**Issue by ccarns** [mxenabled/atrium-csharp#16]
**Enhancement request:** The BaseUrl of the service call is hardcoded to https://vestibule.mx.com - which is problematic when switching between dev and prod.

If you modified `AtriumClient()` initializer to include BaseUrl at least as an optional parameter would be nice. Ideally, it should just be required.

_PS Thanks for fixing the Merchants issue_

**Comment by brettmortensen** [comment]
@ccarns Thanks for reaching out with this issue. 

I've just added an optional third parameter where dev and prod can be specified here: https://github.com/mxenabled/atrium-csharp/pull/17 (It will default to the dev environment if it is left out)

It is now available in the latest release 1.10.3 👍
