### ISSUE TITLE
Method Not Found

### ISSUE THREAD

**Issue by ethanbonin** [mxenabled/atrium-csharp#21]
I get the following error when trying to run any method inside Atrium.dll: 
```C#
System.MissingMethodException: Method not found: 'RestSharp.IRestRequest RestSharp.RestRequest.AddFile(System.String, System.Action`1<System.IO.Stream...
```

__Steps to reproduce__
1. Download Atrium-Csharp project
2. run `build.sh`
3. Move the newly created `Atrium.dll` file to relevant directory in your own project
4. Include the `Atrium.dll` in `ItemGroup` in `project.csproj`
```XML
<Reference Include="Atrium">
   <HintPath>.\Frameworks\Atrium.dll</HintPath>
</Reference>
```
5. Download nugget packages `RestSharp v106.11.7`, `Newtonsoft.Json v13.0.1`, `JsonSubTypes v1.8.0`.
6. Now run any method from the Atrium package
__In my case, I am running the `CreateUser` function__ 
```C#
var Client = new AtriumClient(ClientId, ApiKey, BaseUrl);
var response = Client.users.CreateUser(new UserCreateRequestBody(new User()
{
    Identifier = id,
    IsDisabled = false,
    Metadata = ""
}));
```
It will then throw an error that method not found from rest sharp.

**Comment by brettmortensen** [comment]
Hi @ethanbonin!

Thanks for reaching out and providing detailed reproduction details. This Atrium library is currently pinned to RestSharp `105.1.0`. I received the error you mentioned above when using `106.11.7`. Switching to `105.1.0` resolved the error.

Also a heads up in case this applies to your situation - the MX Platform API is not compatible with these Atrium libraries. Atrium is an older API that we still support, but we are no longer accepting new registrations. The MX Platform API is our latest API, but unfortunately we do not have any wrapper libraries at this time.

**Comment by ethanbonin** [comment]
@brettmortensen, Awesome! Thank you for letting me know!
